name: Preface deploy documentation
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.x
          opam-depext-flags: --with-doc

      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune build @doc
      - run: mkdir -p _build/default/_doc/_html/images
      - run: cp .github/figures/* _build/default/_doc/_html/images

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./_build/default/_doc/_html/
          external_repository: ocaml-preface/ocaml-preface.github.io
          publish_branch: master
          enable_jekyll: false
